Repository operate-first/blog, pull requests merged in 2022-06, with the labels that each got.

#13 remove leftovers
  content/posts/hello-world/index.mdx
  src/@lekoarts/gatsby-theme-minimal-blog/texts/bottom.mdx
Labels: size/S

#14 read.me - add link to blog
  README.md
Labels: lgtm, approved, area/community, kind/website, size/XS

#16 Blog post trip report for KubeCon Valencia EU 2022
  content/posts/kubecon-valencia-eu-2022-trip-report/coufal-twitter.png
  content/posts/kubecon-valencia-eu-2022-trip-report/index.md
Labels: size/L

#17 bump caching to v3
  .github/workflows/build_job.yaml
Labels: size/S

#20 add coloring book blog placeholder
  content/posts/sre-coloring-book/index.mdx
Labels: lgtm, approved, size/S
